export {};

declare global {
  /**
   * Represents all valid LiftKit color tokens.
   */
  type LkColor =
    | "primary"
    | "onprimary"
    | "primarycontainer"
    | "onprimarycontainer"
    | "secondary"
    | "onsecondary"
    | "secondarycontainer"
    | "onsecondarycontainer"
    | "tertiary"
    | "ontertiary"
    | "tertiarycontainer"
    | "ontertiarycontainer"
    | "error"
    | "onerror"
    | "errorcontainer"
    | "onerrorcontainer"
    | "background"
    | "onbackground"
    | "surface"
    | "onsurface"
    | "surfacevariant"
    | "onsurfacevariant"
    | "shadow"
    | "inversesurface"
    | "scrim"
    | "inverseonsurface"
    | "inverseprimary"
    | "success"
    | "onsuccess"
    | "successcontainer"
    | "onsuccesscontainer"
    | "warning"
    | "onwarning"
    | "warningcontainer"
    | "onwarningcontainer"
    | "info"
    | "oninfo"
    | "infocontainer"
    | "oninfocontainer"
    | "primaryfixed"
    | "onprimaryfixed"
    | "primaryfixeddim"
    | "onprimaryfixedvariant"
    | "secondaryfixed"
    | "onsecondaryfixed"
    | "secondaryfixeddim"
    | "onsecondaryfixedvariant"
    | "tertiaryfixed"
    | "ontertiaryfixed"
    | "tertiaryfixeddim"
    | "ontertiaryfixedvariant"
    | "surfacedim"
    | "surfacebright"
    | "surfacecontainerlowest"
    | "surfacecontainerlow"
    | "surfacecontainer"
    | "surfacecontainerhigh"
    | "surfacecontainerhighest"
    | "outline"
    | "outlinevariant"
    | "transparent";

  /**
   * Represents a subset of LiftKit color tokens that have explicitly defined "on-" swatches to match them.
   */
  type LkColorWithOnToken =
    | "primary"
    | "primarycontainer"
    | "secondary"
    | "secondarycontainer"
    | "tertiary"
    | "tertiarycontainer"
    | "error"
    | "errorcontainer"
    | "success"
    | "successcontainer"
    | "warning"
    | "warningcontainer"
    | "info"
    | "infocontainer"
    | "background"
    | "surface"
    | "surfacevariant"
    | "surfacecontainerlowest"
    | "surfacecontainerlow"
    | "surfacecontainer"
    | "surfacecontainerhigh"
    | "surfacecontainerhighest"
    | "inversesurface"
    | "transparent"

  type LkOnColor =
    | "onprimary"
    | "onprimarycontainer"
    | "onsecondary"
    | "onsecondarycontainer"
    | "ontertiary"
    | "ontertiarycontainer"
    | "onerror"
    | "onerrorcontainer"
    | "onsuccess"
    | "onsuccesscontainer"
    | "onwarning"
    | "onwarningcontainer"
    | "oninfo"
    | "oninfocontainer"
    | "onbackground"
    | "onsurface"
    | "onsurfacevariant"
    | "inverseonsurface";
}
